### ISSUE TITLE
Fix blog URL referenced

### ISSUE THREAD

**Issue by fishbits** [rfennell/VSTSPowershell#1]
In VSTSPowershell/REST/TCMReplacement.ps1 ...should be:
http://blogs.blackmarble.co.uk/blogs/rfennell/post/2016/09/27/Running-Test-Suites-within-a-network-Isolated-Lab-Management-environment-when-using-TFS-vNext-build-and-release-tooling

Thanks for this, btw!!!

**Comment by rfennell** [comment]
Thanks I have a few of these, an upgrade to our blog server changed a few urls
